import os

from telethon.sync import TelegramClient
from telethon.tl.functions.account import UploadWallPaperRequest
from telethon.tl.types import InputFile, WallPaperSettings

from config.api_keys import API_ID, API_HASH, NAME

api_id = API_ID
api_hash = API_HASH

async def adjust_color_brightness(hex_color, factor=0.1):
    # Перетворюємо рядок у форматі "#RRGGBB" у відповідне ціле число.
    color = int(hex_color[1:], 16)

    # Розділяємо колір на компоненти: червоний, зелений і синій.
    red = (color >> 16) & 0xFF
    green = (color >> 8) & 0xFF
    blue = color & 0xFF

    # Обчислюємо інтенсивність коліру. Ми використовуємо середню інтенсивність RGB.
    brightness = (red + green + blue) / 3.0

    # Визначаємо, чи колір є світлим чи темним, використовуючи порігове значення 128.
    if brightness < 128:
        # Колір темний, отже, ми освітлюємо його на заданий коефіцієнт.
        new_red = int(red + (255 - red) * factor)
        new_green = int(green + (255 - green) * factor)
        new_blue = int(blue + (255 - blue) * factor)
    else:
        # Колір світлий, отже, ми затемнюємо його на заданий коефіцієнт.
        new_red = int(red * (1 - factor))
        new_green = int(green * (1 - factor))
        new_blue = int(blue * (1 - factor))

    # Запобігаємо виходу за межі 0-255 для кожного компонента.
    new_red = max(0, min(255, new_red))
    new_green = max(0, min(255, new_green))
    new_blue = max(0, min(255, new_blue))

    # Формуємо новий колір у форматі "#RRGGBB" і повертаємо його.
    new_color = "#{:02X}{:02X}{:02X}".format(new_red, new_green, new_blue)
    return new_color


async def create_iphone_theme(chat_id, image_path, bg, dark, status_bar, primary_txt, not_primary_txt):
    async with TelegramClient('annon', api_id, api_hash) as client:
        result = await client.upload_file(image_path)
        darker_bg = await adjust_color_brightness(bg)
        darker_bg =darker_bg[1:]
        secondary_txt = await adjust_color_brightness(primary_txt)
        secondary_txt = secondary_txt[1:]
        bg = bg[1:]
        primary_txt = primary_txt[1:]
        not_primary_txt = not_primary_txt[1:]
        
        keyboard = 'light'
        if status_bar == 'light':
            keyboard = 'black'

        if result:
            input_file = InputFile(
                id=result.id,
                parts=result.parts,
                name=result.name,
                md5_checksum=result.md5_checksum
            )

            wallpaper = await client(UploadWallPaperRequest(
                file=input_file,
                mime_type='image/jpeg',
                settings=WallPaperSettings()
            ))

            wallpaper_slug = wallpaper.slug
            name = f'{status_bar}_{bg}'
            file_name = f'{NAME}_{bg}{primary_txt}{not_primary_txt}.tgios-theme'

            path = os.path.join('ios', 'theme', str(chat_id))
            if not os.path.exists(path):
                os.makedirs(path)

            theme = os.path.join('ios', 'theme', str(chat_id), file_name)
            
            ios_data = [
                f"",
                f"name: {name}",
                f"basedOn: day",
                f"dark: {dark}",
                f"intro:",
                f"statusBar: {status_bar}",
                f"primaryText: {primary_txt}",
                f"accentText: {not_primary_txt}",
                f"disabledText: 33{secondary_txt}",
                f"startButton: {not_primary_txt}",
                f"dot: 5e5e5e",
                f"passcode:",
                f"  bg:",
                f"    top: {darker_bg}",
                f"    bottom: {darker_bg}",
                f"  button: clear",
                f"root:",
                f"  statusBar: {status_bar}",
                f"  tabBar:",
                f"    background: {darker_bg}",
                f"    separator: 33{not_primary_txt}",
                f"    icon: a1{not_primary_txt}",
                f"    selectedIcon: {not_primary_txt}",
                f"    text: a1{not_primary_txt}",
                f"    selectedText: {not_primary_txt}",
                f"    badgeBackground: {primary_txt}",
                f"    badgeStroke: {darker_bg}",
                f"    badgeText: {darker_bg}",
                f"  navBar:",
                f"    button: {not_primary_txt}",
                f"    disabledButton: 33{not_primary_txt}",
                f"    primaryText: {primary_txt}",
                f"    secondaryText: {secondary_txt}",
                f"    control: {not_primary_txt}",
                f"    accentText: {not_primary_txt}",
                f"    background: {darker_bg}",
                f"    separator: 33{not_primary_txt}",
                f"    badgeFill: {primary_txt}",
                f"    badgeStroke: {darker_bg}",
                f"    badgeText: ffffff",
                f"  searchBar:",
                f"    background: {darker_bg}",
                f"    accent: {not_primary_txt}",
                f"    inputFill: 33d6d6d6",
                f"    inputText: 000000",
                f"    inputPlaceholderText: a1{not_primary_txt}",
                f"    inputIcon: 33000000",
                f"    inputClearButton: 7b7b81",
                f"    separator: 33{not_primary_txt}",
                f"  keyboard: {keyboard}",
                f"list:",
                f"  blocksBg: {darker_bg}",
                f"  plainBg: {darker_bg}",
                f"  primaryText: {primary_txt}",
                f"  secondaryText: {secondary_txt}",
                f"  disabledText: 1e{not_primary_txt}",
                f"  accent: {not_primary_txt}",
                f"  highlighted: 1e{not_primary_txt}",
                f"  destructive: ff3b30",
                f"  placeholderText: c8c8ce",
                f"  itemBlocksBg: {darker_bg}",
                f"  itemHighlightedBg: 1e{not_primary_txt}",
                f"  blocksSeparator: 33{not_primary_txt}",
                f"  plainSeparator: 33{not_primary_txt}",
                f"  disclosureArrow: bab9be",
                f"  sectionHeaderText: 6d6d72",
                f"  freeText: 6d6d72",
                f"  freeTextError: cf3030",
                f"  freeTextSuccess: 26972c",
                f"  freeMonoIcon: 7e7e87",
                f"  switch:",
                f"    frame: e0e0e0",
                f"    handle: ffffff",
                f"    content: 77d572",
                f"    positive: 00c900",
                f"    negative: ff3b30",
                f"  disclosureActions:",
                f"    neutral1:",
                f"      bg: {not_primary_txt}",
                f"      fg: ffffff",
                f"    neutral2:",
                f"      bg: f09a37",
                f"      fg: ffffff",
                f"    destructive:",
                f"      bg: ff3824",
                f"      fg: ffffff",
                f"    constructive:",
                f"      bg: 00c900",
                f"      fg: ffffff",
                f"    accent:",
                f"      bg: {not_primary_txt}",
                f"      fg: ffffff",
                f"    warning:",
                f"      bg: ff9500",
                f"      fg: ffffff",
                f"    inactive:",
                f"      bg: bcbcc3",
                f"      fg: ffffff",
                f"  check:",
                f"    bg: {not_primary_txt}",
                f"    stroke: c7c7cc",
                f"    fg: ffffff",
                f"  controlSecondary: dedede",
                f"  freeInputField:",
                f"    bg: {darker_bg}",
                f"    stroke: {darker_bg}",
                f"    placeholder: 96979d",
                f"    primary: {primary_txt}",
                f"    control: {not_primary_txt}",
                
                # f"  mediaPlaceholder: e4e4e4",
                
                f"  mediaPlaceholder: {bg}",
                f"  scrollIndicator: 4c000000",
                f"  pageIndicatorInactive: e3e3e7",
                f"  inputClearButton: cccccc",
                f"chatList:",
                f"  bg: {darker_bg}",
                f"  itemSeparator: 33{not_primary_txt}",
                f"  itemBg: 1ed6d6d6",
                f"  pinnedItemBg: {darker_bg}",
                f"  itemHighlightedBg: 1e{not_primary_txt}",
                f"  itemSelectedBg: 1e{not_primary_txt}",
                f"  title: {primary_txt}",
                f"  secretTitle: 00b12c",
                f"  dateText: {secondary_txt}",
                f"  authorName: {secondary_txt}",
                f"  messageText: {secondary_txt}",
                f"  messageDraftText: {secondary_txt}",
                f"  checkmark: {not_primary_txt}",
                f"  pendingIndicator: {secondary_txt}",
                f"  failedFill: ff3b30",
                f"  failedFg: ffffff",
                f"  muteIcon: {secondary_txt}",
                f"  unreadBadgeActiveBg: {not_primary_txt}",
                f"  unreadBadgeActiveText: ffffff",
                f"  unreadBadgeInactiveBg: b6b6bb",
                f"  unreadBadgeInactiveText: ffffff",
                f"  pinnedBadge: {not_primary_txt}",
                f"  pinnedSearchBar: e5e5e5",
                f"  regularSearchBar: e9e9e9",
                f"  sectionHeaderBg: 33d6d6d6",
                f"  sectionHeaderText: 8e8e93",
                f"  verifiedIconBg: {not_primary_txt}",
                f"  verifiedIconFg: ffffff",
                f"  secretIcon: 00b12c",
                f"  pinnedArchiveAvatar:",
                f"    background:",
                f"      top: 1e{not_primary_txt}",
                f"      bottom: {not_primary_txt}",
                f"    foreground: ffffff",
                f"  unpinnedArchiveAvatar:",
                f"    background:",
                f"      top: 1e{secondary_txt}",
                f"      bottom: {secondary_txt}",
                f"    foreground: ffffff",
                f"  onlineDot: 4cc91f",
                f"chat:",
                f"  defaultWallpaper: {wallpaper_slug}",
                f"  message:",
                f"    incoming:",
                f"      bubble:",
                f"        withWp:",
                f"          bg: {darker_bg}",
                f"          highlightedBg: ccdadade",
                f"          stroke: {darker_bg}",
                f"        withoutWp:",
                f"          bg: {darker_bg}",
                f"          highlightedBg: ccdadade",
                f"          stroke: {darker_bg}",
                f"      primaryText: {primary_txt}",
                f"      secondaryText: {secondary_txt}",
                f"      linkText: {not_primary_txt}",
                f"      linkHighlight: 1e{not_primary_txt}",
                f"      scam: ff3b30",
                f"      textHighlight: 1e{not_primary_txt}",
                f"      accentText: {not_primary_txt}",
                f"      accentControl: {not_primary_txt}",
                f"      mediaActiveControl: {not_primary_txt}",
                f"      mediaInactiveControl: cacaca",
                f"      pendingActivity: 99{bg}",
                f"      fileTitle: {not_primary_txt}",
                f"      fileDescription: 999999",
                f"      fileDuration: 99525252",
                f"      mediaPlaceholder: f2f2f2",
                f"      polls:",
                f"        radioButton: c8c7cc",
                f"        radioProgress: {not_primary_txt}",
                f"        highlight: 1e{not_primary_txt}",
                f"        separator: c8c7cc",
                f"        bar: {not_primary_txt}",
                f"      actionButtonsBg:",
                f"        withWp: 66a5a5a5",
                f"        withoutWp: ccffffff",
                f"      actionButtonsStroke:",
                f"        withWp: clear",
                f"        withoutWp: {not_primary_txt}",
                f"      actionButtonsText:",
                f"        withWp: ffffff",
                f"        withoutWp: {not_primary_txt}",
                f"      textSelection: 4c{not_primary_txt}",
                f"      textSelectionKnob: {not_primary_txt}",
                f"    outgoing:",
                f"      bubble:",
                f"        withWp:",
                f"          bg: {bg}",
                f"          highlightedBg: ccdadade",
                f"          stroke: {bg}",
                f"        withoutWp:",
                f"          bg: {bg}",
                f"          highlightedBg: ccdadade",
                f"          stroke: {bg}",
                f"      primaryText: ffffff",
                f"      secondaryText: a5ffffff",
                f"      linkText: ffffff",
                f"      linkHighlight: 4cffffff",
                f"      scam: ffffff",
                f"      textHighlight: 4cffffff",
                f"      accentText: ffffff",
                f"      accentControl: ffffff",
                f"      mediaActiveControl: ffffff",
                f"      mediaInactiveControl: a5ffffff",
                f"      pendingActivity: a5{bg}",
                f"      fileTitle: ffffff",
                f"      fileDescription: a5ffffff",
                f"      fileDuration: a5ffffff",
                f"      mediaPlaceholder: {primary_txt}",
                f"      polls:",
                f"        radioButton: a5ffffff",
                f"        radioProgress: ffffff",
                f"        highlight: 1effffff",
                f"        separator: a5ffffff",
                f"        bar: ffffff",
                f"      actionButtonsBg:",
                f"        withWp: 66a5a5a5",
                f"        withoutWp: ccffffff",
                f"      actionButtonsStroke:",
                f"        withWp: clear",
                f"        withoutWp: {not_primary_txt}",
                f"      actionButtonsText:",
                f"        withWp: ffffff",
                f"        withoutWp: {not_primary_txt}",
                f"      textSelection: 33ffffff",
                f"      textSelectionKnob: ffffff",
                f"    freeform:",
                f"      withWp:",
                f"        bg: e5e5ea",
                f"        highlightedBg: dadade",
                f"        stroke: e5e5ea",
                f"      withoutWp:",
                f"        bg: e5e5ea",
                f"        highlightedBg: dadade",
                f"        stroke: e5e5ea",
                f"    infoPrimaryText: 000000",
                f"    infoLinkText: {primary_txt}",
                f"    outgoingCheck: ffffff",
                f"    mediaDateAndStatusBg: 7f000000",
                f"    mediaDateAndStatusText: ffffff",
                f"    shareButtonBg:",
                f"      withWp: 66a5a5a5",
                f"      withoutWp: ccffffff",
                f"    shareButtonStroke:",
                f"      withWp: clear",
                f"      withoutWp: e5e5ea",
                f"    shareButtonFg:",
                f"      withWp: ffffff",
                f"      withoutWp: {not_primary_txt}",
                f"    mediaOverlayControl:",
                f"      bg: 99000000",
                f"      fg: ffffff",
                f"    selectionControl:",
                f"      bg: {not_primary_txt}",
                f"      stroke: c7c7cc",
                f"      fg: ffffff",
                f"    deliveryFailed:",
                f"      bg: ff3b30",
                f"      fg: ffffff",
                f"    mediaHighlightOverlay: 99ffffff",
                f"  serviceMessage:",
                f"    components:",
                f"      withDefaultWp:",
                f"        bg: ccffffff",
                f"        primaryText: 8d8e93",
                f"        linkHighlight: 3f748391",
                f"        scam: ff3b30",
                f"        dateFillStatic: ccffffff",
                f"        dateFillFloat: ccffffff",
                f"      withCustomWp:",
                f"        bg: 66a5a5a5",
                f"        primaryText: ffffff",
                f"        linkHighlight: 3f748391",
                f"        scam: ff3b30",
                f"        dateFillStatic: 66a5a5a5",
                f"        dateFillFloat: 44a5a5a5",
                f"    unreadBarBg: ffffff",
                f"    unreadBarStroke: ffffff",
                f"    unreadBarText: 8d8e93",
                f"    dateText:",
                f"      withWp: ffffff",
                f"      withoutWp: 8d8e93",
                f"  inputPanel:",
                f"    panelBg: {darker_bg}",
                f"    panelSeparator: 33{not_primary_txt}",
                f"    panelControlAccent: {not_primary_txt}",
                f"    panelControl: {secondary_txt}",
                f"    panelControlDisabled: 1e{secondary_txt}",
                f"    panelControlDestructive: ff3b30",
                f"    inputBg: 1ed6d6d6",
                f"    inputStroke: {darker_bg}",
                f"    inputPlaceholder: 33{secondary_txt}",
                f"    inputText: {primary_txt}",
                f"    inputControl: {not_primary_txt}",
                f"    actionControlBg: {not_primary_txt}",
                f"    actionControlFg: ffffff",
                f"    primaryText: {primary_txt}",
                f"    secondaryText: {secondary_txt}",
                f"    mediaRecordDot: {not_primary_txt}",
                f"    mediaRecordControl:",
                f"      button: {not_primary_txt}",
                f"      micLevel: 1e{not_primary_txt}",
                f"      activeIcon: ffffff",
                f"  inputMediaPanel:",
                f"    panelSeparator: bec2c6",
                f"    panelIcon: 858e99",
                f"    panelHighlightedIconBg: 33858e99",
                f"    stickersBg: e8ebf0",
                f"    stickersSectionText: 9099a2",
                f"    stickersSearchBg: d9dbe1",
                f"    stickersSearchPlaceholder: 8e8e93",
                f"    stickersSearchPrimary: 000000",
                f"    stickersSearchControl: 8e8e93",
                f"    gifsBg: ffffff",
                f"  inputButtonPanel:",
                f"    panelBg: dee2e6",
                f"    panelSeparator: bec2c6",
                f"    buttonBg: ffffff",
                f"    buttonStroke: c3c7c9",
                f"    buttonHighlightedBg: a8b3c0",
                f"    buttonHighlightedStroke: c3c7c9",
                f"    buttonText: 000000",
                f"  historyNav:",
                f"    bg: {darker_bg}",
                f"    stroke: {darker_bg}",
                f"    fg: {primary_txt}",
                f"    badgeBg: {not_primary_txt}",
                f"    badgeStroke: {not_primary_txt}",
                f"    badgeText: ffffff",
                f"actionSheet:",
                f"  dim: 66000000",
                f"  bgType: light",
                f"  opaqueItemBg: ffffff",
                f"  itemBg: ddffffff",
                f"  opaqueItemHighlightedBg: e5e5e5",
                f"  itemHighlightedBg: b2e5e5e5",
                f"  opaqueItemSeparator: e5e5e5",
                f"  standardActionText: {not_primary_txt}",
                f"  destructiveActionText: ff3b30",
                f"  disabledActionText: b3b3b3",
                f"  primaryText: 000000",
                f"  secondaryText: 5e5e5e",
                f"  controlAccent: {not_primary_txt}",
                f"  inputBg: e9e9e9",
                f"  inputHollowBg: ffffff",
                f"  inputBorder: e4e4e6",
                f"  inputPlaceholder: 818086",
                f"  inputText: 000000",
                f"  inputClearButton: 7b7b81",
                f"  checkContent: ffffff",
                f"contextMenu:",
                f"  dim: 33000a26",
                f"  background: c6f9f9f9",
                f"  itemSeparator: 333c3c43",
                f"  sectionSeparator: 338a8a8a",
                f"  itemBg: 00000000",
                f"  itemHighlightedBg: 333c3c43",
                f"  primary: 000000",
                f"  secondary: cc000000",
                f"  destructive: ff3b30",
                f"notification:",
                f"  bg: ffffff",
                f"  primaryText: 000000",
                f"  expanded:",
                f"    bgType: light",
                f"    navBar:",
                f"      background: ffffff",
                f"      primaryText: 000000",
                f"      control: 7e8791",
                f"      separator: b1b1b1",

            ]

            with open(theme, 'w') as f:
                for row in ios_data:
                    f.write(str(row) + '\n')

    return theme
